### ISSUE TITLE
License

### ISSUE THREAD

**Issue by riccardocagnasso** [diovudau/pynsm2#6]
Can you provide this software with a more permissive license than LGPLv3?

I've written a small gui wrapper to alsa_out and I would like to distribute it under a permissive licence like WTFPL or MIT. Problem is that since you don't want to provide a packaged version of this library, I have to include it in the codebase. That, as far as I undestand, I can't do under LGPLv3. This leaves me with two options.

- Use GPL / LGPL for my software, which I would really like not to do (and I think that's is not what is your original intention to enforce, since you use Lgpl and not GPL)
- upload my previous fork of your library that package it with setuptools to pypi and use that in my software.

Neither this would be ideal. Since from the fact that you are using LESSER gpl I deduce that you original intended to allow people to use this library in non-GPL code, could you please provide this code licensed via MIT or equivalent?

**Comment by diovudau** [comment]
Sure, why not. I'll change it soon but you can assume WTFPL already.

**Comment by riccardocagnasso** [comment]
Thank you very much.
